"""Correlation-aware soft-information fusion.

Why the legacy fusion is wrong here
-----------------------------------
The legacy composite deflection is

    D_q = (sum_l w_l delta_l)^2 / (sum_l w_l^2 sigma_l^2),

which is only valid when the local statistics are mutually independent.  A
multi-UAV bistatic network violates that in at least five ways, and always in
the direction of *positive* correlation:

* two pairs share the same transmitter ``i`` -- same waveform, same phase noise
  and the same self-interference residual;
* two pairs share the same receiver ``j`` -- same noise floor, same
  direct-link cancellation residual, same residual-interference term;
* every pair sees the *same* target, so the Swerling fluctuation is a shared
  latent variable rather than an independent draw per link;
* two targets landing in the same or neighbouring delay-Doppler support share
  leakage;
* the echoes are generated by one physical scatterer.

Ignoring this makes a set of redundant links look as informative as a set of
geometrically diverse ones, which is why the paper had to bolt on hand-set
geometric-diversity factors and repeated-observation penalties.

The fix
-------
With the covariance ``Sigma_q`` of the stacked local statistics, the fused
deflection of a linear statistic ``w^T s`` is

    D_q(w) = (w^T delta)^2 / (w^T Sigma_q w),

maximised by

    w* propto Sigma_q^{-1} delta,        D_q* = delta^T Sigma_q^{-1} delta.

Correlated / redundant observations are then automatically down-weighted by
the maths instead of by a heuristic.

Construction of Sigma
---------------------
``Sigma = S R S`` with ``S = diag(sigma_l)`` and ``R`` a *sum of positive
semi-definite factors* with unit diagonal:

    R = (1 - rho_tx - rho_rx - rho_tgt - rho_dd) I
        + rho_tx  B_tx      B_tx[l,l'] = 1{i_l = i_l'}
        + rho_rx  B_rx      B_rx[l,l'] = 1{j_l = j_l'}
        + rho_tgt J         all-ones (shared target fluctuation)
        + rho_dd  K_dd      K_dd = Laplace kernel product on the DD bins

``B_tx`` and ``B_rx`` are Gram matrices of one-hot indicator vectors, ``J =
11^T``, and ``K_dd = exp(-|dl|/kappa) * exp(-|dk|/kappa)`` is a tensor product
of two Laplace kernels.  Every term is PSD and the coefficients are
non-negative, so ``R`` is PSD by construction -- no eigenvalue repair needed.
The residual weight on ``I`` is the idiosyncratic (genuinely independent)
share; the configuration is renormalised if the ``rho``s sum above one.
"""

from __future__ import annotations

from typing import Dict, List, Sequence, Tuple

import numpy as np

from .config import Config, Link
from .model import BaseGains

EPS = 1e-12


def _rhos(cfg: Config) -> Tuple[float, float, float, float]:
    """Normalised (rho_tx, rho_rx, rho_target, rho_dd), guaranteed to sum <= 1."""
    c = cfg.corr
    raw = [
        max(float(c.rho_tx), 0.0),
        max(float(c.rho_rx), 0.0),
        max(float(c.rho_target), 0.0),
        max(float(c.rho_dd), 0.0),
    ]
    total = sum(raw)
    if total > 1.0:
        raw = [r / total for r in raw]
    return raw[0], raw[1], raw[2], raw[3]


def dd_laplace_kernel(
    delay_bin: Sequence[int],
    doppler_bin: Sequence[int],
    kappa: float = 1.0,
) -> np.ndarray:
    """PSD kernel on the delay-Doppler grid: product of two Laplace kernels."""
    l = np.asarray(delay_bin, dtype=float)
    k = np.asarray(doppler_bin, dtype=float)
    dl = np.abs(l[:, None] - l[None, :])
    dk = np.abs(k[:, None] - k[None, :])
    return np.exp(-dl / max(kappa, EPS)) * np.exp(-dk / max(kappa, EPS))


def correlation_matrix(
    cfg: Config,
    links: Sequence[Link],
    delay_bin: Sequence[int] | None = None,
    doppler_bin: Sequence[int] | None = None,
) -> np.ndarray:
    """Unit-diagonal correlation matrix of the local statistics in ``links``."""
    n = len(links)
    if n == 0:
        return np.zeros((0, 0), dtype=float)
    rho_tx, rho_rx, rho_tgt, rho_dd = _rhos(cfg)

    tx = np.array([link[0] for link in links])
    rx = np.array([link[1] for link in links])
    B_tx = (tx[:, None] == tx[None, :]).astype(float)
    B_rx = (rx[:, None] == rx[None, :]).astype(float)
    J = np.ones((n, n), dtype=float)

    R = (1.0 - rho_tx - rho_rx - rho_tgt - rho_dd) * np.eye(n)
    R = R + rho_tx * B_tx + rho_rx * B_rx + rho_tgt * J
    if rho_dd > 0.0 and delay_bin is not None and doppler_bin is not None:
        R = R + rho_dd * dd_laplace_kernel(delay_bin, doppler_bin)
    # Enforce an exact unit diagonal (the construction already gives one up to
    # floating-point noise; this keeps the idiosyncratic share well defined).
    np.fill_diagonal(R, 1.0)
    return 0.5 * (R + R.T)


def link_dd_bins(
    cfg: Config,
    base: BaseGains | None,
    q: int,
    links: Sequence[Link],
) -> Tuple[List[int], List[int]]:
    """Delay / Doppler bin indices of ``links`` for target ``q``."""
    if base is None:
        return [0] * len(links), [0] * len(links)
    return (
        [int(base.delay_bin[i, j, q]) for i, j in links],
        [int(base.doppler_bin[i, j, q]) for i, j in links],
    )


def covariance_matrix(
    cfg: Config,
    links: Sequence[Link],
    sigma: np.ndarray,
    base: BaseGains | None = None,
    q: int | None = None,
) -> np.ndarray:
    """Full covariance ``Sigma = S R S`` of the stacked local statistics."""
    R = correlation_matrix(
        cfg,
        links,
        *(link_dd_bins(cfg, base, q if q is not None else 0, links) if base is not None else (None, None))
    )
    S = np.asarray(sigma, dtype=float)
    return R * np.outer(S, S)


def solve_psd(A: np.ndarray, b: np.ndarray) -> np.ndarray:
    """Solve ``A x = b`` for a PSD ``A``, with a ridge / pinv fallback."""
    n = A.shape[0]
    try:
        return np.linalg.solve(A + 1e-10 * np.eye(n), b)
    except np.linalg.LinAlgError:  # pragma: no cover - defensive
        return np.linalg.pinv(A) @ b


def correlation_aware_weights(
    cfg: Config,
    links: Sequence[Link],
    delta: np.ndarray,
    sigma: np.ndarray,
    base: BaseGains | None = None,
    q: int | None = None,
) -> np.ndarray:
    r"""Deflection-optimal weights ``w propto Sigma^{-1} delta``, normalised.

    Falls back to the independent-observation rule ``w propto delta/sigma^2``
    when the correlation model is switched off or the system is 1-dimensional.
    """
    delta = np.asarray(delta, dtype=float)
    sigma = np.asarray(sigma, dtype=float)
    n = len(links)
    if n == 0:
        return np.zeros(0, dtype=float)
    if (not cfg.corr.enable) or n == 1:
        w = np.maximum(delta, 0.0) / (sigma ** 2 + EPS)
        total = float(np.sum(w))
        return w / total if total > EPS else np.full(n, 1.0 / n)

    Sigma = covariance_matrix(cfg, links, sigma, base=base, q=q)
    w = solve_psd(Sigma, delta)
    # A negative weight can appear when a link is *more* correlated with the
    # rest than it is informative; clamping keeps the fused statistic a
    # convex combination, which is what the Monte-Carlo detector assumes.
    w = np.maximum(w, 0.0)
    total = float(np.sum(w))
    if total <= EPS:
        return np.full(n, 1.0 / n)
    return w / total


def correlated_deflection(
    cfg: Config,
    links: Sequence[Link],
    delta: np.ndarray,
    sigma: np.ndarray,
    weights: np.ndarray,
    base: BaseGains | None = None,
    q: int | None = None,
) -> float:
    """Fused deflection ``(w^T delta)^2 / (w^T Sigma w)``."""
    delta = np.asarray(delta, dtype=float)
    w = np.asarray(weights, dtype=float)
    num = float(w @ delta)
    if num <= 0.0:
        return 0.0
    if cfg.corr.enable and len(links) > 1:
        Sigma = covariance_matrix(cfg, links, sigma, base=base, q=q)
        den = float(w @ Sigma @ w)
    else:
        den = float(np.sum((w ** 2) * (np.asarray(sigma, dtype=float) ** 2)))
    return float(num * num / (den + EPS))


def redundancy_index(
    cfg: Config,
    links: Sequence[Link],
    delta: np.ndarray,
    sigma: np.ndarray,
    base: BaseGains | None = None,
    q: int | None = None,
) -> float:
    """How much of the naive (independence-assuming) deflection is spurious.

    ``1 - D_corr / D_ind`` in ``[0, 1)``: ``0`` means the links are genuinely
    independent, values approaching ``1`` mean the naive fusion was counting
    the same information several times.  Useful as a diagnostic and as an
    ablation axis.
    """
    if len(links) == 0:
        return 0.0
    if not cfg.corr.enable or len(links) == 1:
        return 0.0
    w = correlation_aware_weights(cfg, links, delta, sigma, base=base, q=q)
    d_corr = correlated_deflection(cfg, links, delta, sigma, w, base=base, q=q)
    s = np.asarray(sigma, dtype=float)
    d_ind = float(np.sum((np.asarray(delta, dtype=float) ** 2) / (s ** 2 + EPS)))
    if d_ind <= EPS:
        return 0.0
    return float(max(0.0, 1.0 - d_corr / d_ind))
